  type t = Big_int.big_int
  let to_string_in_hexa = BatBig_int.to_string_in_hexa
  let string_of_big_int = Big_int.string_of_big_int
  let big_int_of_string = Big_int.big_int_of_string
  let hex_to_big_int h = Big_int.big_int_of_string ("0x"^h)
  let eq_big_int = Big_int.eq_big_int
  let big_int_of_int = Big_int.big_int_of_int
  let zero_big_int = Big_int.zero_big_int
  let unit_big_int = Big_int.unit_big_int
  let sub_big_int = Big_int.sub_big_int
